# Generated by Django 4.2.1 on 2023-10-01 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='consulting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام')),
                ('lastName', models.CharField(max_length=30, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=13, verbose_name='شماره تماس')),
                ('company', models.CharField(max_length=50, verbose_name='شرکت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ و زمان')),
                ('active', models.BooleanField(default=False, verbose_name='پاسخ داده شده / پاسخ نداده شده')),
                ('category', models.ManyToManyField(to='CRM.category', verbose_name='عنوان')),
            ],
        ),
    ]
