# Generated by Django 5.0.9 on 2024-09-20 20:17

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('name', models.CharField(max_length=40, verbose_name='نام')),
                ('last_Name', models.CharField(max_length=40, verbose_name='نام خانوادگي')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='نام كاربري')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=13, verbose_name='تلفن')),
                ('country', models.CharField(max_length=20, verbose_name='کشور')),
                ('city', models.CharField(max_length=20, verbose_name='شهر')),
                ('email', models.EmailField(max_length=60, verbose_name='ایمیل')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(blank=True, max_length=20, null=True, verbose_name='جنسیت')),
                ('education', models.CharField(blank=True, max_length=50, null=True, verbose_name='تحصیلات')),
                ('social_media', models.CharField(blank=True, max_length=50, null=True, verbose_name='ای دی شبکه اجتماعی')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس')),
                ('is_EmailVerified', models.BooleanField(default=False)),
                ('is_Business', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default=account.models.get_default_profile_image, max_length=255, null=True, upload_to=account.models.get_profile_image_filepath)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ver_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('code', models.CharField(max_length=6)),
                ('offer', models.BooleanField(default=False)),
                ('offerId', models.PositiveIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
