# Generated by Django 5.0.7 on 2024-09-15 22:02

import account.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('name', models.CharField(max_length=40, verbose_name='نام')),
                ('last_Name', models.CharField(max_length=40, verbose_name='نام خانوادگي')),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='نام كاربري')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=13, verbose_name='تلفن')),
                ('country', models.CharField(max_length=20, verbose_name='کشور')),
                ('city', models.CharField(max_length=20, verbose_name='شهر')),
                ('email', models.EmailField(max_length=60, verbose_name='ایمیل')),
                ('birthday', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('gender', models.CharField(blank=True, max_length=20, null=True, verbose_name='جنسیت')),
                ('education', models.CharField(blank=True, max_length=50, null=True, verbose_name='تحصیلات')),
                ('social_media', models.CharField(blank=True, max_length=50, null=True, verbose_name='ای دی شبکه اجتماعی')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='آدرس')),
                ('is_EmailVerified', models.BooleanField(default=False)),
                ('is_Business', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, default=account.models.get_default_profile_image, max_length=255, null=True, upload_to=account.models.get_profile_image_filepath)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='نام دسته بندی')),
                ('Maincategory', models.CharField(choices=[('فروشگاه', 'فروشگاه'), ('خدمات', 'خدمات'), ('تولیدی', 'تولیدی')], max_length=20, verbose_name='نوع کسب و کار')),
            ],
        ),
        migrations.CreateModel(
            name='sitesToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteUrl', models.CharField(max_length=100)),
                ('Token', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ver_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11)),
                ('code', models.CharField(max_length=6)),
                ('offer', models.BooleanField(default=False)),
                ('offerId', models.PositiveIntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('B_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام کسب و کار ')),
                ('subscription', models.PositiveIntegerField(default=1, verbose_name='ای دی اشتراک')),
                ('expiration', models.DateTimeField(blank=True, null=True, verbose_name='انقضای اشتراک')),
                ('SMS_number', models.IntegerField(default=100, verbose_name='تعداد اس ام اس')),
                ('Nationalcode', models.CharField(max_length=20, verbose_name='کد ملی')),
                ('web_address', models.CharField(blank=True, max_length=200, null=True)),
                ('social_network', models.CharField(blank=True, max_length=200, null=True)),
                ('shop_address', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=300, null=True)),
                ('B_phone', models.CharField(max_length=13, verbose_name='تلفن')),
                ('Business_level', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D'), ('e', 'E')], default='e', max_length=20, verbose_name='امتیاز')),
                ('online', models.BooleanField(default=None, null=True)),
                ('ofline', models.BooleanField(default=None, null=True)),
                ('VIP', models.BooleanField(blank=True, null=True)),
                ('profile_image', models.ImageField(blank=True, default=account.models.get_default_profile_image, max_length=255, null=True, upload_to=account.models.upload_image_path)),
                ('sms_template', models.PositiveIntegerField(default=100000, verbose_name='کد قالب sms')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(blank=True, to='account.category', verbose_name=' دسته کسب و کار ')),
            ],
        ),
    ]
