# Generated by Django 5.0.9 on 2024-10-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='education',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_Business',
        ),
        migrations.RemoveField(
            model_name='account',
            name='social_media',
        ),
        migrations.AddField(
            model_name='account',
            name='postal_code',
            field=models.CharField(default=1, max_length=20, verbose_name='کد پستی'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='تلفن'),
        ),
    ]
