# Generated by Django 5.0.9 on 2024-10-03 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_account_education_remove_account_is_business_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='firstName',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='last_Name',
            new_name='last_name',
        ),
    ]
