# Generated by Django 5.0.9 on 2024-10-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_specialorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialorder',
            name='phone',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
