# Generated by Django 5.0.9 on 2024-10-21 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_specialorder_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.PositiveBigIntegerField(default=0, max_length=2),
        ),
    ]
