# Generated by Django 5.0.9 on 2024-10-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.ManyToManyField(related_name='special', to='shop.product')),
            ],
        ),
    ]
