# Generated by Django 5.0.2 on 2024-04-01 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('telegram', models.CharField(max_length=25)),
                ('whatsapp', models.CharField(max_length=25)),
                ('instagram', models.CharField(max_length=25)),
                ('eitaa', models.CharField(max_length=25)),
            ],
        ),
    ]
