# Generated by Django 5.0.2 on 2024-04-01 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
