# Generated by Django 5.0.7 on 2024-09-15 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Seller', models.CharField(default='استارتاپ  ارسی', max_length=20, verbose_name='فروشنده')),
                ('Seller_National_Code', models.CharField(default='111', max_length=11, verbose_name='شناسه ملی')),
                ('paid', models.BooleanField(default=False, verbose_name='وضعیت پرداخت')),
                ('price', models.PositiveBigIntegerField(verbose_name='قیمت')),
                ('discount', models.PositiveBigIntegerField(verbose_name='تخفیف')),
                ('price_after_discount', models.PositiveIntegerField(verbose_name='قیمت بعد از اعمال تخفیف')),
                ('Taxation', models.PositiveBigIntegerField(verbose_name='مالیات')),
                ('final_price', models.PositiveBigIntegerField(verbose_name='قیمت نهایی')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('Expiration_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انقضا')),
                ('authority', models.CharField(max_length=50)),
                ('buyerBussiness', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='account.business')),
                ('products', models.ManyToManyField(related_name='products', to='Products.product')),
            ],
        ),
    ]
