# Generated by Django 5.0 on 2024-04-04 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
